### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by anuraghazra** [casesandberg/react-color#591] opened 2019-02-19 13:45 UTC
I think this is why preventDefault() is not working in mobile devices #590.

![react-color](https://user-images.githubusercontent.com/35374649/53019195-3288ee80-347a-11e9-9611-970296d9dec6.PNG)

**Comment by casesandberg** [comment] 2019-02-21 22:22
Do you have some time to dig into this an put up a PR with a solution?

**Comment by casesandberg** [comment] 2019-02-21 23:33
Closing as duplicate of https://github.com/casesandberg/react-color/issues/581

**Closed by casesandberg** 2019-02-21 23:33 UTC
Labels: bug, help wanted

**Comment by anuraghazra** [comment] 2019-02-22 10:01
Okay, I will try to give it a go hopefully fixing the bug.
