### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by Murphycx94** [casesandberg/react-color#660] opened 2019-12-01 12:30 UTC
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

**Comment by djrumbold** [comment] 2019-12-06 01:47
This is a duplicate of #634

**Comment by casesandberg** [comment] 2020-01-08 17:28
This was fixed with #662 and will be released shortly as react-color@2.18.0

**Closed by casesandberg** 2020-01-08 17:28 UTC
