### ISSUE TITLE
Error extending styles

### ISSUE THREAD

**Issue by zhangyanling77** [casesandberg/react-color#567] opened 2019-01-07 02:58 UTC
> in Sketch.js, var styles = (0, _reactcss2.default)((0, _merge2.default)({ 'default': _extends({ picker: { width: width, padding: '10px 10px 0', boxSizing: 'initial', background: '#fff', borderRadius: '4px', boxShadow: '0 0 0 1px rgba(0,0,0,.15), 0 8px 16px rgba(0,0,0,.15)', position: 'relative', zIndex: 99 },...),should add {position: 'relative', zIndex: 99}

**Comment by jakobsandberg** [comment] 2019-01-07 05:32
Looks like you're pointing to the built JS for this guy: https://github.com/casesandberg/react-color/blob/master/src/components/sketch/Sketch.js#L14. Is that correct?

Why do we want to add `position: 'relative', zIndex: 99`? Is there a context where your picker is hidden? If so, please provide steps to reproduce the bug.

**Comment by casesandberg** [comment] 2019-01-23 22:05
Are you still having problems with this? Can you please provide code to reproduce this>

**Comment by casesandberg** [comment] 2019-04-27 01:04
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.

**Closed by casesandberg** 2019-04-27 01:04 UTC
Labels: need more info, needs author update
