### ISSUE TITLE
SliderPicker throwing style error with ReactJS

### ISSUE THREAD

**Issue by ReesesSnickers** [casesandberg/react-color#585] opened 2019-02-06 21:06 UTC
Error:
The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
    in div (created by Slider)
    in Slider (created by ColorPicker)
    in ColorPicker (at App.js:392)
    in div (at App.js:385)
    in div (at App.js:164)
    in App (at src/index.js:7)

Code:
```
import React from 'react';
import './App.css'
import { SliderPicker } from 'react-color';

class App extends React.Component {
  constructor(props){
    super(props);
    this.state = {
sliderColor: {
        r: '255',
        g: '255',
        b: '255',
        a: '1',
      }
    };
  }

handleSliderChange = (color) => {
    this.setState({
     sliderColor: color.rgb
    })
 }

render() {
    return (
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between"
          }}
        >
          <SliderPicker
              color={ this.state.sliderColor }
              onChange={ this.handleSliderPickerChange }
          />
          <div 
            style={{
              backgroundColor: `rgba(${ this.state.sliderColor.r }, ${ this.state.sliderColor.g }, ${ this.state.sliderColor.b }, ${ this.state.sliderColor.a })`,
              borderRadius: "50%",
              width: "200px",
              height: "200px",
              marginRight: "50px"
            }}
          />
        </div>
      </div>
    );
  }
}

 export default App;
```

When I comment out the 
```
<SliderPicker
     color={ this.state.sliderColor }
     onChange={ this.handleSliderPickerChange }
/>
```
the issue goes away.

**Comment by dakotalightning** [comment] 2019-02-10 16:29
I'm getting the same error.

**Comment by stianbakken** [comment] 2019-02-11 09:36
Same error here aswell.

**Comment by Crizzooo** [comment] 2019-02-19 21:38
Any update on this? Slider component is completely unusable, in what Im assuming are newer versions of React...

**Comment by casesandberg** [comment] 2019-02-21 22:19
You cant use the SliderPicker with the style prop or the SliderPicker doesn't work at all? I am using master with: this code and I cant seem to reproduce any issues:
```
<Slider 
    style={{ marginRight: 4 + 'em' }} 
    color={ 'red' }
    onChange={ console.log }
/>
```
Can you help me debug this by pasting some code examples?

**Comment by samus42** [comment] 2019-02-26 18:34
I get the issue on latest of react-color, and i'm just using simple color and onChange (not providing style).  I also tried putting in a style property, and still got the error.

<SliderPicker onChange={onChangeColor} color={selectedColor} />

This works fine on version 2.14.1 and under.  Its only when I jump to 2.17.0 that it breaks

**Comment by g-s-k** [comment] 2019-02-27 17:35
Also getting this error. [Here is a minimal example.](https://github.com/g-s-k/react-color-slider-error-example) I'm using the SliderPicker with [no props](https://github.com/g-s-k/react-color-slider-error-example/blob/962cbd5b4bb73412a6e141c741b38fcca631462f/src/App.js#L5).

**Comment by cokencode** [comment] 2019-03-05 14:47
@casesandberg New version needs to be published. The latest version `v2.17.0` on `npm`  was shipped before the fix #566

**Comment by PHCodes** [comment] 2019-03-23 12:49
I'm also still having this issue.

**Comment by danielloczi** [comment] 2019-03-29 07:49
Hi @casesandberg! As @cokencode suggested, could you please ship a new npm package? 
Bug #585 makes impossible to use this library without the fix #566 !

**Comment by krisxcrash** [comment] 2019-04-18 21:32
I am also having the same issue when trying to use SliderPicker.

**Comment by usama-jamil** [comment] 2019-04-19 06:11
`<Modal.Content>
                  <Label content="Primary Color" />
                  <SliderPicker/>

                  <Label content="Secondary Color" />
                  {/* <SliderPicker/> */}
              </Modal.Content>
`
i am  also getting same error on version "react-color": "^2.14.1"
should i update version

**Comment by casesandberg** [comment] 2019-04-20 20:12
Apologies. Looks like the root package.json version didn't get updated. This means I have been publishing versions under 2.16.X for the past few months. This has been fixed and deployed a new version at `react-color@2.17.1`

**Comment by casesandberg** [comment] 2019-04-27 01:00
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.

**Closed by casesandberg** 2019-04-27 01:00 UTC
Labels: can't reproduce, need more info, needs author update
