### ISSUE TITLE
react-color is largest dependency in my project

### ISSUE THREAD

**Issue by bryanlarsen** [casesandberg/react-color#72] opened 2016-01-18 11:39 UTC
from webpack-bundle-size-analyzer:

```
react-color: 685.36 kB (30.4%)
  lodash: 401.81 kB (58.6%)
    <self>: 401.81 kB (100%)
  material-colors: 4.51 kB (0.659%)
    <self>: 4.51 kB (100%)
  reactcss: 3.71 kB (0.541%)
    <self>: 3.71 kB (100%)
  merge: 2.8 kB (0.409%)
    <self>: 2.8 kB (100%)
  <self>: 272.52 kB (39.8%)
```

react itself clocked in at 628kB (27.8%).

I recommend switching to modularized lodash:  https://www.npmjs.com/browse/keyword/lodash-modularized

**Comment by casesandberg** [comment] 2016-01-18 19:08
This is a duplicate of https://github.com/casesandberg/react-color/issues/59 that I treid to fix but it seems I didnt do it correctly. I will dig into this so that you can import just the color picker you want to use.

**Comment by bryanlarsen** [comment] 2016-01-18 19:09
@casesandberg, no this is a completely separate issue.   #59 won't help very much, because it still includes all of lodash.  switching out lodash for lodash-modularized will immediately cut ~66% of the cut for a few minutes of effort.

**Comment by casesandberg** [comment] 2016-01-18 19:12
Oh, I see what you are saying. I will make sure to get that in today!

**Comment by casesandberg** [comment] 2016-01-19 05:08
This has been done in https://github.com/casesandberg/react-color/pull/73 and you can grab it from npm at `react-color@1.3.1`

**Closed by casesandberg** 2016-01-19 05:08 UTC
Labels: in progress
