### ISSUE TITLE
Problem with Redux

### ISSUE THREAD

**Issue by remy-poirier** [casesandberg/react-color#322] opened 2017-01-26 17:11 UTC
Hello I am trying to use this library with Redux, but I have to click two times on the color in order to get it displayed (I try with CirclePicker), but the action is dispatched on the first click as expected.

How can I get the good color displayed on the first click ? And why does it work at the second one ?

I call it like 

`<CirclePicker
                                style={{"margin":"0 auto"}}
                                onChangeComplete={createCategoryColor}
                            />`

And the method called simply does 
`createCategoryColor(color, event){
        const { dispatch } = this.props;
        dispatch(selectColorCreate(color.hex));
    }`

Do you have any idea please ? This lib is really nice !

**Comment by casesandberg** [comment] 2017-01-31 00:43
You have to pass down the color from redux into the component:
```
<CirclePicker color={reduxColorVar} style={{"margin":"0 auto"}} onChangeComplete={createCategoryColor} />
```

**Comment by casesandberg** [comment] 2017-03-05 06:13
Going to close this. Please re-open if it's still an issue!

**Closed by casesandberg** 2017-03-05 06:13 UTC
Labels: need more info, needs author update

**Comment by efdor** [comment] 2017-04-03 21:00
I'm having problems using one of the react-color color pickers, as well.

When I use the picker in the form like this:
    <SliderPicker name="color" color={this.props.color}/>

the 'submit' function doesn't pick up the value... 

When I make a custom field like this:

colorSlider = ({ input, label, meta: { touched, error } }) => (
	<div className={styles.row} style={{width:'50%'}}>
		<label>{label}</label>
		<SliderPicker {...input} />
		<span className={touched && error ? styles.error : styles.hidden}>{error}</span>
	</div>
)
and declare a Field:
    <Field name="color" label="Text Color" component={colorSlider}/>

Then the value is picked up by 'submit', but the color picker acts up and doesn't let me select colors in the same way that the normal component works... What am I doing wrong?

**Comment by casesandberg** [comment] 2017-04-04 00:47
Are you talking about Submit in a form? React color currently doesnt work in a form natively, you have to get the state from its onChange callback.

**Comment by efdor** [comment] 2017-04-04 11:47
Ok, I tried this as well:

`<div className={styles.row} style={{width:'50%'}}>
				<label>{label}</label>
				<SliderPicker onChange={
						(color) => {
							props.change(fieldName, color.hex)
						}
				} />
				<Field name={fieldName} component="hidden" />
			</div>`

redux form still captures the value. but the SliderPicker is still acting up. I can't select some colors and the sliding doesn't seem to work at all, rather you need to click on the spectrum to change the color. When I click on another field, the slider returns to the initial color.

**Comment by efdor** [comment] 2017-04-04 11:53
Others seem to work fine, it must be a more specific problem with the SliderPicker. I haven't tested with others like it though.

**Comment by casesandberg** [comment] 2017-04-05 22:22
You also have to pass the active color down into the component:

```
<div className={styles.row} style={{width:'50%'}}>
  <label>{label}</label>
  <SliderPicker color={ FIELD_NAME_HEX_COLOR_VAR } onChange={ (color) => { props.change(fieldName, color.hex) } } /> 
  <Field name={fieldName} component="hidden" /> 
</div>
```

**Comment by spencersmb** [comment] 2017-08-31 22:11
That worked great @casesandberg and @efdor - thanks!

**Comment by pradeepgill007** [comment] 2017-10-24 09:41
Hi @casesandberg the problem is still there as I have to click two times on the color in order to get it displayed.

`const colorSlider = ({
    input,
    label,
    meta: {
        touched,
        error
    },
    ...custom
}) => (<div style={{width:'50%'}}>
  <BlockPicker {...input} {...custom}/> 
</div>
 )`

`<Field
                                        color={item.value}
                                        triangle="hide"
                                        colors={['#000', '#ff0000']}
                                        item={item}
                                        name={item.key}
                                        component={colorSlider}/>`
