### ISSUE TITLE
Disable opacity on Chrome and Sketch pickers

### ISSUE THREAD

**Issue by jeffchienzabinet** [casesandberg/react-color#240] opened 2016-09-22 03:08 UTC
This is an awesome project. I want to use some of the prebuilt pickers, but my use case doesn't include editing the opacity/alpha channel. It would be great if it were possible to disable opacity/alpha on these pickers even if it means not being exactly like the pickers they were inspired from.

**Comment by casesandberg** [comment] 2016-09-22 20:15
Yep! This is a dupe of https://github.com/casesandberg/react-color/issues/99, you can use:

```
<ChromePicker disableAlpha="true" />
<SketchPicker disableAlpha="true" />
```

I have also created this issue to make sure this gets in the documentation! https://github.com/casesandberg/react-color/issues/241

**Closed by casesandberg** 2016-09-22 20:15 UTC

**Comment by careerwale** [comment] 2020-12-01 18:36
This link is helpful. Just one more query if we use <SketchPicker disableAlpha="true" /> it will disable opacity part from palette. But it will not change height of palette. How would I decrease height of div class 'flexbox-fix' in palette.  So that we can remove extra height. Can someone please help to decrease height after disableAlpha="true" ?
