### ISSUE TITLE
css property unit issue with react 15.1.0

### ISSUE THREAD

**Issue by jma7889** [casesandberg/react-color#164] opened 2016-06-02 17:04 UTC
I got lots of warnings such as:

 `    Warning: a `div` tag (owner: `Saturation`) was passed a numeric string value for CSS property `top` (value: `0`) which will be treated as a unitless number in a future version of React.`

They are also from 'chrome, hue, alpha, and checkboard'. I use version 2.1.0 of react-color. Any fix yet?

**Comment by cthorner** [comment] 2016-06-02 19:33
duplicate of #153 ?

**Comment by jma7889** [comment] 2016-06-03 14:15
It is duplicate. I am waiting for the npm release

**Comment by casesandberg** [comment] 2016-08-24 16:01
This is fixed if you update to the latest version!

**Closed by casesandberg** 2016-08-24 16:01 UTC
