### ISSUE TITLE
Error when Change HSL in ChromePicker

### ISSUE THREAD

**Issue by aircloud** [casesandberg/react-color#520] opened 2018-07-02 09:03 UTC
Maybe there is an error when changing HSL in ChromePicker:

when I changing the 's' and 'l' In HSL mode in HSL mode in ChromePicker, I find that the value will be zeroed（there are something wrong）so I read the source code:

```
/src/components/chrome/ChromeFields.js Line 72:
        h: data.h || this.props.hsl.h,
        s: Number((data.s && data.s) || this.props.hsl.s),
        l: Number((data.l && data.l) || this.props.hsl.l),
        source: 'hsl',
```

`data.s` is a string, '20%' for instance.

so `Number((data.s && data.s) || this.props.hsl.s)` is syntax error. 

If needed, I can make a pull request to fix it.

**Comment by zhengcanbiao** [comment] 2018-08-21 03:40
I meet the same problem，hope to fix this HSL value setting bug

**Comment by casesandberg** [comment] 2018-09-29 16:56
Fantastic catch! I would love it if you could make a PR with this change!

**Comment by MariamBashir** [comment] 2018-10-04 10:30
Hi, has anyone worked on this, i would be fine with opening a PR for this?

**Comment by jakobsandberg** [comment] 2019-01-07 08:53
@aircloud were you explicitly seeing that syntax error in your console?

In the case when `data.s` is a string, we strip out the `%` character before coercing the string into a number:
```
if (typeof(data.s) === 'string' && data.s.includes('%')) { data.s = data.s.replace('%', '') }
```
So in your example, we would simply be doing `Number('20')` which coerces the string `'20'` into the number `20`.

It also looks like `Number` should not be giving a syntax error when you pass it a string, even if it's a "garbage" string like `'20%'`. Just as a sanity check I tried `Number('20%')` and it yielded `NaN`, which could cause issues down the road, but should not be breaking at this line.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number (look at example 10 with the input `'100a'`)

**Comment by jakobsandberg** [comment] 2019-01-07 08:57
My bad, looks like the source code changed since you opened the ticket.

Looks like this is a dupe of #528, which was fixed by [this commit](https://github.com/casesandberg/react-color/commit/05306c1dbe1ccc6f6d672b495e5ff6b86821dabf#diff-565ca46e19066591c308205cd952291e).

@casesandberg can we close this guy and #528?

**Comment by casesandberg** [comment] 2019-04-27 01:14
I am going to go ahead and close this. If you are still having an issue please try using the newest version of this package. Otherwise, you can open a new issue.

**Closed by casesandberg** 2019-04-27 01:14 UTC
Labels: bug, needs author update
