### ISSUE TITLE
1.3.3 breaks everything browserify-related

### ISSUE THREAD

**Issue by grassick** [casesandberg/react-color#77] opened 2016-01-20 14:59 UTC
You used to be able to do:
```
var ColorPicker = require('react-color');
```

as in the Readme

Now you have to do:

```
var ColorPicker = require('react-color').ColorPicker;
```

Since exports.default is not supported.

Could you perhaps bump to version 2.0 since it has significant changes to usage for browserify at least?

**Comment by casesandberg** [comment] 2016-01-20 15:33
That's not good. I will revert to the old export method so that there is no breaking changes

**Comment by timothyallan** [comment] 2016-01-20 16:36
Ahhh that's why things started dying in my app. Thanks in advance for reverting it @casesandberg

**Comment by casesandberg** [comment] 2016-01-20 16:56
Yep. This is a duplicate of https://github.com/casesandberg/react-color/issues/76#issuecomment-173266631 so I am going to close this and put updates there.

**Closed by casesandberg** 2016-01-20 16:56 UTC
