### ISSUE TITLE
Alpha value textbox incorrect after first removing focus

### ISSUE THREAD

**Issue by nt1m** [casesandberg/react-color#492] opened 2018-03-29 08:21 UTC
See https://github.com/mozilla/Themer/issues/159

**Comment by elvisvoer** [comment] 2018-04-01 14:47
@nt1m can you try a build with the latest version because I cannot reproduce it in the latest version and the docs website is outdated.

**Comment by lmorchard** [comment] 2018-04-04 20:50
Yeah, I'm thinking this has more to do with how we're trying to normalize values than an upstream issue with this component

**Comment by casesandberg** [comment] 2019-01-23 23:37
Going to close this as it seems it has been resolved

**Closed by casesandberg** 2019-01-23 23:37 UTC
