### ISSUE TITLE
Regression after v2.13.5 - Cursor jumps around at some specific values

### ISSUE THREAD

**Issue by earslap** [casesandberg/react-color#548] opened 2018-10-05 11:10 UTC
When picking gray values very close to white, the cursor jumps to irrelevant colors at some places.

This issue is still present in 3.0 betas from what I see.

This is a working barebones example with v2.13.5
https://codesandbox.io/s/l46ynywk7m

And the same example with v2.13.7 (same behaviour persists in all future versions)
https://codesandbox.io/s/8n7nm221w2

**Gifs showing behaviour:**
Working as expected (v2.13.5):

![working](https://user-images.githubusercontent.com/121476/46532111-4dcad700-c8a8-11e8-9ffe-944261b2b987.gif)

The issue (v2.13.7+):

![not_working](https://user-images.githubusercontent.com/121476/46532132-5c18f300-c8a8-11e8-9ce3-b1e1574961b0.gif)

This also happens in other pickers, not just the Chrome one.

**Comment by shio-yaamaa** [comment] 2018-10-12 16:22
I think the cause of this problem is as follows:

The `Saturation` component, on which you move around your cursor in the GIF, converts the cursor position to HSV in `src/helpers/saturation.js`. At this point, its S and V are denoted as percentages, which means they range from 0 to 100.

This HSV value is passed to `handleChange()` in `src/components/common/ColorWrap.js`, then to `toState` in `src/helpers/color.js`. This function calls `tinycolor`’s constructor with this HSV value.

When the value of S or V is between 0 and 1, though it’s meant to be a percentage (ranges from 0 to 100), `tinycolor` interprets it as a decimal (ranges from 0 to 1). When it’s larger than 1, `tinycolor` interprets it as a percentage as expected.

Example:

```javascript
tinycolor{{
  h: 0,
  s: 50,
  v: 100
}}.toHsv()
```

and

```javascript
tinycolor({
  h: 0,
  s: 0.5,
  v: 100
}).toHsv()
```

both yield

```javascript
{
  h: 0,
  s: 0.5,
  v: 1
}
```

though the second one is meant to be

```javascript
{
  h: 0,
  s: 0.005,
  v: 1
}
```

So, when your cursor is between 0 and 1 (on either axis), the value gets scaled by factor 100, which causes the sudden cursor jumps.

## Quick fix

Specify the unit of S and V when calling the constructor:

```javascript
tinycolor({
  h: 0,
  s: '0.5%',
  v: '100%'
}).toHsv()
```

Related: #539

**Comment by shio-yaamaa** [comment] 2018-10-12 16:27
This problem is mentioned in #539 :)

**Comment by casesandberg** [comment] 2019-01-23 22:21
This is a duplicate of https://github.com/casesandberg/react-color/issues/216. We are tracking this issue in the 3.0.0 version we are working on here: https://github.com/casesandberg/react-color/issues/404

**Closed by casesandberg** 2019-01-23 22:21 UTC
