### ISSUE TITLE
when color prop set cursor does not work

### ISSUE THREAD

**Issue by nadimtuhin** [casesandberg/react-color#35] opened 2015-09-01 12:37 UTC
this code does not work

```javascript
import React 'react';
import ReactColor from 'react-color';


class ColorPicker extends React.Component {

  constructor() {
    super();
    this.state = {
      value: '#fff'
    };

    this.handleChangeComplete = this.handleChangeComplete.bind(this);
  }

  handleChangeComplete(color) {
    this.setState({value: color.hex});
  }

  render() {
    return <ReactColor color={ this.state.value }
                       type="sketch"
                       onChangeComplete={ this.handleChangeComplete } />;
  }
}

export default ColorPicker;
```

**Comment by adeelraza** [comment] 2015-09-01 17:12
Duplicate of #34 - the problem is not setting the default color but it breaks if the color is #fff or #000

**Comment by casesandberg** [comment] 2015-09-13 16:58
This was fixed in `react-color@1.0.6`

**Closed by casesandberg** 2015-09-13 16:58 UTC
